#!/bin/bash
   
#PBS -q express
#PBS -P er4
#PBS -N data_extraction
#PBS -l walltime=24:00:00
#PBS -l ncpus=48
#PBS -l mem=190gb
#PBS -o /g/data/er4/zk6340/code/Script_Hydro-projections/PBS_jobs/hp_data_extraction.out
#PBS -e /g/data/er4/zk6340/code/Script_Hydro-projections/PBS_jobs/hp_data_extraction.error
#PBS -m e
#PBS -l storage=gdata/wj02+gdata/er4
#PBS -M zaved.khan@bom.gov.au

# Source AWRA v6 (updated non-stripy parameters)
source /g/data/er4/AWRACMS/gadi_activate_awra_v6.1_lisa

# Run simulation
path=/g/data/er4/zk6340/code/Script_Hydro-projections

# Run simulation
nohup python $path/007a_hp_data_extraction.py 1>$path/PBS_jobs/007a_hp_data_extraction.log 2>$path/PBS_jobs/007a_hp_data_extraction.err 